chat_model_name: Qwen/Qwen3-Coder-480B-A35B-Instruct
embedding_model_name: BAAI/bge-m3  
siliconflow_base_url: https://api.siliconflow.cn/v1
siliconflow_api_key: sk-zvtscuctixdnvgmxapggfhdammatebsqoogggscahmyebpvv
